version: '3.8'

services:
  snailmail:
    build: .
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:2567/hello_world"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s