{{- if .Values.imageUpdate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snailmail.fullname" . }}-updater
  labels:
    {{- include "snailmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "snailmail.fullname" . }}-updater
  labels:
    {{- include "snailmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "snailmail.fullname" . }}-updater
  labels:
    {{- include "snailmail.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-updater
subjects:
- kind: ServiceAccount
  name: {{ include "snailmail.fullname" . }}-updater
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "snailmail.fullname" . }}-updater
  apiGroup: rbac.authorization.k8s.io
{{- end }}