apiVersion: apps/v1
kind: Deployment
metadata:
  name: snailmail-server
  labels:
    app: snailmail-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snailmail-server
  template:
    metadata:
      labels:
        app: snailmail-server
    spec:
      containers:
      - name: snailmail-server
        image: harbor.rackspace.koski.co/snailmail:latest
        ports:
        - containerPort: 2567
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /hello_world
            port: 2567
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hello_world
            port: 2567
          initialDelaySeconds: 5
          periodSeconds: 5