name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: snailmail-set
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Match package.json requirements (>= 20.9.0)
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
