name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: snailmail-set
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Or your project's node version
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run format # Assuming you have a format script in package.json
      - name: Run tests # Add this step if you have tests
        run: npm test # Assuming you have a test script in package.json
